/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "spell_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




SpellRequest::~SpellRequest() throw() {
}


void SpellRequest::__set_to_check(const std::vector<std::string> & val) {
  this->to_check = val;
}

const char* SpellRequest::ascii_fingerprint = "ACE4F644F0FDD289DDC4EE5B83BC13C0";
const uint8_t SpellRequest::binary_fingerprint[16] = {0xAC,0xE4,0xF6,0x44,0xF0,0xFD,0xD2,0x89,0xDD,0xC4,0xEE,0x5B,0x83,0xBC,0x13,0xC0};

uint32_t SpellRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->to_check.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->to_check.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += iprot->readString(this->to_check[_i4]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.to_check = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SpellRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("SpellRequest");

  xfer += oprot->writeFieldBegin("to_check", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->to_check.size()));
    std::vector<std::string> ::const_iterator _iter5;
    for (_iter5 = this->to_check.begin(); _iter5 != this->to_check.end(); ++_iter5)
    {
      xfer += oprot->writeString((*_iter5));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(SpellRequest &a, SpellRequest &b) {
  using ::std::swap;
  swap(a.to_check, b.to_check);
  swap(a.__isset, b.__isset);
}

SpellRequest::SpellRequest(const SpellRequest& other6) {
  to_check = other6.to_check;
  __isset = other6.__isset;
}
SpellRequest& SpellRequest::operator=(const SpellRequest& other7) {
  to_check = other7.to_check;
  __isset = other7.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const SpellRequest& obj) {
  using apache::thrift::to_string;
  out << "SpellRequest(";
  out << "to_check=" << to_string(obj.to_check);
  out << ")";
  return out;
}


SpellResponse::~SpellResponse() throw() {
}


void SpellResponse::__set_is_correct(const std::vector<bool> & val) {
  this->is_correct = val;
}

const char* SpellResponse::ascii_fingerprint = "32DC9F1EC2D276BDA69B3700356C9E85";
const uint8_t SpellResponse::binary_fingerprint[16] = {0x32,0xDC,0x9F,0x1E,0xC2,0xD2,0x76,0xBD,0xA6,0x9B,0x37,0x00,0x35,0x6C,0x9E,0x85};

uint32_t SpellResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->is_correct.clear();
            uint32_t _size8;
            ::apache::thrift::protocol::TType _etype11;
            xfer += iprot->readListBegin(_etype11, _size8);
            this->is_correct.resize(_size8);
            uint32_t _i12;
            for (_i12 = 0; _i12 < _size8; ++_i12)
            {
              xfer += iprot->readBool(this->is_correct[_i12]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.is_correct = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t SpellResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("SpellResponse");

  xfer += oprot->writeFieldBegin("is_correct", ::apache::thrift::protocol::T_LIST, 1);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_BOOL, static_cast<uint32_t>(this->is_correct.size()));
    std::vector<bool> ::const_iterator _iter13;
    for (_iter13 = this->is_correct.begin(); _iter13 != this->is_correct.end(); ++_iter13)
    {
      xfer += oprot->writeBool((*_iter13));
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(SpellResponse &a, SpellResponse &b) {
  using ::std::swap;
  swap(a.is_correct, b.is_correct);
  swap(a.__isset, b.__isset);
}

SpellResponse::SpellResponse(const SpellResponse& other14) {
  is_correct = other14.is_correct;
  __isset = other14.__isset;
}
SpellResponse& SpellResponse::operator=(const SpellResponse& other15) {
  is_correct = other15.is_correct;
  __isset = other15.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const SpellResponse& obj) {
  using apache::thrift::to_string;
  out << "SpellResponse(";
  out << "is_correct=" << to_string(obj.is_correct);
  out << ")";
  return out;
}


